<testsuite errors="0" failures="1" name="nose2-junit" skipped="0" tests="2" time="0.001">
  <testcase classname="tests_example.Test" name="test_soma" time="0.000123">
    <system-out />
  </testcase>
  <testcase classname="tests_example.Test" name="test_sub" time="0.000103">
    <failure message="test failure">Traceback (most recent call last):
  File "/home/z4r4tu5tr4/git/jenkins-blue-ocean-python-tests/tests/tests_example.py", line 10, in test_sub
    self.assertEqual(add(1, 1), 0)
AssertionError: 2 != 0
</failure>
    <system-out />
  </testcase>
</testsuite>
